baseURL = 'https://tech.blogandbeyond.com/'
languageCode = 'en-us'
title = 'Blog And Beyond:  Compact Tech'
theme = 'PaperMod'

enableRobotsTXT = true
enableEmoji = true

[params]
  env = "production"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = false
  ShowToc = false
  ShowFullTextinRSS = true
  
  [params.homeInfoParams]
    Title = "Blog And Beyond:  Compact Tech"
    Content = "Daily AI-powered insights. Pure information. No sales pitch."
  
  [params.label]
    text = "Blog And Beyond: "
    icon = "/icons/favicon.png"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
