baseURL = 'https://blogandbeyond.com/'
locale = 'en-us'
title = 'Blog and Beyond'
theme = 'PaperMod'

[params]
  env = "production"
  ShowReadingTime = false
  ShowShareButtons = false
  ShowBreadCrumbs = false
  ShowToc = false
  ShowFullTextinRSS = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
